In [8]:
import tensorflow as tf
import torch
import numpy as np

In [38]:
m = np.random.rand(10000, 10000)

In [57]:
tf_dense = tf.convert_to_tensor(m)
torch_dense = torch.as_tensor(m).requires_grad_(True)

In [58]:
print(tf_dense)
print(torch_dense)

tf.Tensor(
[[0.86811831 0.881722   0.69852798 ... 0.59969897 0.6298199  0.88126884]
 [0.78352466 0.56474207 0.97278842 ... 0.08052143 0.67444153 0.93692923]
 [0.38449655 0.29601248 0.69453924 ... 0.72261993 0.51019155 0.40803703]
 ...
 [0.61880906 0.44419511 0.79446361 ... 0.29342362 0.9685631  0.50507456]
 [0.44589419 0.7840496  0.86119082 ... 0.56705047 0.09034566 0.63058939]
 [0.67211527 0.22808715 0.80289122 ... 0.99147399 0.85212772 0.96080815]], shape=(10000, 10000), dtype=float64)
tensor([[0.8681, 0.8817, 0.6985,  ..., 0.5997, 0.6298, 0.8813],
        [0.7835, 0.5647, 0.9728,  ..., 0.0805, 0.6744, 0.9369],
        [0.3845, 0.2960, 0.6945,  ..., 0.7226, 0.5102, 0.4080],
        ...,
        [0.6188, 0.4442, 0.7945,  ..., 0.2934, 0.9686, 0.5051],
        [0.4459, 0.7840, 0.8612,  ..., 0.5671, 0.0903, 0.6306],
        [0.6721, 0.2281, 0.8029,  ..., 0.9915, 0.8521, 0.9608]],
       dtype=torch.float64, requires_grad=True)


In [63]:
torch.gather(torch_dense, 0, torch.as_tensor(0)).sum().backward()
torch_dense.grad

RuntimeError: invalid argument 4: Index tensor must have same dimensions as input tensor at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:638

In [62]:
with tf.GradientTape() as gen_tape:
    gen_tape.watch(tf_dense)
    out = tf.reduce_sum(tf.gather(tf_dense, [0, 1]))

gradients_gen = gen_tape.gradient(out, tf_dense)
print(gradients_gen)
print()
print(tf.convert_to_tensor(gradients_gen))

IndexedSlices(indices=tf.Tensor([0 1], shape=(2,), dtype=int32), values=tf.Tensor(
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]], shape=(2, 10000), dtype=float64), dense_shape=tf.Tensor([10000 10000], shape=(2,), dtype=int32))

tf.Tensor(
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(10000, 10000), dtype=float64)
